name: postman

on: push

jobs: 
  newman:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
#    - name: Checkout develop
 #     run: git checkout develop
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: actions/cache@v1
      id: cache
      with:
        path: ~/local/rubies
        key: ${{ runner.os }}-ruby-2.6.3
    - uses: clupprich/ruby-build-action@master
      id: ruby
      with:
        ruby-version: 2.6.3
        cache-available: ${{ steps.cache.outputs.cache-hit == 'true' }}
    - uses: actions/cache@v1
      with:
        path: backend/vendor/bundle
        key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gem-
    - name: Bundle install
      run: |
        cd backend
        gem install bundler:2.0.2
        sudo apt-get -yqq install libsqlite3-dev
        bundle install --jobs=4 --retry=3 --path vendor/bundle
    - name: Load database from schema
      run: |
        cd backend
        bundle exec bin/rails db:schema:load
    - name: Run rails backend
      env:
        RAILS_ENV: test
      run: |
        cd backend
        bundle exec bin/rails s &
    - name: Run newman tests
      run: |
        cd frontend
        yarn add newman
        ls *.json
        node_modules/newman/bin/newman.js run Yabs.postman_collection.json

